#Nếu Có Lỗi Hãy Liên Hệ Qua: https://www.facebook.com/thl.0911 (Hữu Lộc)

#Command: /authmepe reload

#Permissions Cho Admin Là: authmepe.admin (default: op)

#Lưu Ý: Chỉnh Thời Gian Login Của AuthMe Cao Lên Xíu

#tùy chỉnh các tính năng
Setting:
  Prefix: '&r[&bAuthMePE&r]'
  Delay-Open-Menu: 1 #thời gian delay mở Menu-AuthMe-Geyser
  Menu-AuthMe-Geyser: true #bật menu register và login, tắt đi tức là bật skip login
  Password-Login-Geyser: 'AuthMePE' #password mà plugin sẽ dùng để tạo cho các player pe khi bật Skip-AuthMe-Geyser
  Wrong-Kick: false #kick player khi đăng nhập sai mật khẩu
#cấu hình menu
Menu:
  #tùy chỉnh menu đăng ký
  Title-Register: 'Đăng Ký Tài Khoản'
  Title-Register-Password: 'Mật khẩu'
  Input-Register-Placeholder: 'Nhập mật khẩu'
  Title-Register-RePassword: 'Nhập Lại Mật Khẩu'
  Input-Register-RePlaceholder: 'Nhập mật khẩu'
  #tùy chỉnh menu đăng nhập
  Title-Login: "Đăng Nhập Tài Khoản"
  Title-Login-Password: 'Mật khẩu'
  Input-Login-Placeholder: 'Nhập mật khẩu'
#tùy chỉnh các message, placeholder: {prefix}
Message:
  Wrong-Password: '&cSai Mật Khẩu' #thông báo player nếu mật khẩu sai
  Not-Enough: '&cBạn Chưa Điền Đầy Đủ Thông Tin' #thông báo player nếu không đầy đủ thông tin
  Not-Same: '&c2Mật Khẩu Không Giống Nhau' #thông bao player nếu 2 mật khẩu không giống nhau
  Reload-Successful: '{prefix} &aReload Config Thành Công' #reload config thành công
  No-Permissions: '{prefix} &cBạn Không Có Quyền Thực Hiện Lệnh Này' #thông báo không có quyền
  Command-Wrong: '{prefix} &a/authmepe reload |&e Reload Config Plugin' #lệnh không hợp lệ
  Auto-Login: '{prefix} &aTài Khoản Của Bạn Đã Được Đăng Nhập Tự Động'
  Auto-Register: "{prefix} &aTài Khoản Của Bạn Đã Được Đăng Ký Tự Động"
