name: AuthMePE
version: '1.1.2'
main: me.shinthl09.AuthMePE
api-version: 1.19
depend: [ floodgate , AuthMe]
author: ShinTHL09
folia-supported: true
commands:
  authmepe:
    usage: /<command>
    description: "AuthMePE Command"
    aliases: [ athpe ]
permissions:
  authmepe.admin:
    description: "Permissions Cho Admin"
    default: op
